spring:
  application:
    name: nolost
  datasource:
    url: jdbc:postgresql://localhost:5432/nolostdb
    username: postgres
    password: DBpass2025**
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
#    properties:
#      jakarta.persistence.schema-generation.scripts.action: create
#      jakarta.persistence.schema-generation.scripts.create-target: src/main/resources/db/20250325_001.sql
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
      # Generate scripts
      # mvn spring-boot:run -Dspring.jpa.properties.hibernate.hbm2ddl.auto=create
      # move target/schema.sql to src/main/resources/db/scripts/

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema.internal: DEBUG