create table church_role
(
    id   integer generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);
create table member
(
    is_baptized boolean,
    joined_date date    not null,
    role_id     integer not null,
    id          bigint generated by default as identity,
    leader_id   bigint,
    person_id   bigint  not null unique,
    primary key (id)
);
create table membership_process
(
    completed_by integer,
    completed_at timestamp(6),
    id           bigint generated by default as identity,
    person_id    bigint not null,
    step_id      bigint not null,
    status       varchar(255),
    primary key (id)
);
create table mentorship_process
(
    end_date              date,
    start_date            date         not null,
    id                    bigint generated by default as identity,
    membership_process_id bigint       not null unique,
    mentor_id             bigint       not null,
    status                varchar(255) not null,
    primary key (id)
);
create table person
(
    allow_contact          boolean,
    date_of_birth          date         not null,
    is_local_residence     boolean      not null,
    id                     bigint generated by default as identity,
    full_name              varchar(255) not null,
    gender                 varchar(255) not null,
    marital_status         varchar(255),
    residence_neighborhood varchar(255),
    primary key (id)
);
create table process_step
(
    is_active   boolean      not null,
    step_order  integer      not null,
    id          bigint generated by default as identity,
    description varchar(255) not null,
    name        varchar(255) not null,
    primary key (id)
);
alter table if exists member
    add constraint FK_member_leader foreign key (leader_id) references member;
alter table if exists member
    add constraint FK_member_person foreign key (person_id) references person;
alter table if exists member
    add constraint FK_member_role foreign key (role_id) references church_role;
alter table if exists membership_process
    add constraint FK_membership_process_person foreign key (person_id) references person;
alter table if exists membership_process
    add constraint FK_membership_process_process_step foreign key (step_id) references process_step;
alter table if exists mentorship_process
    add constraint FK_mentorship_process_membership_process foreign key (membership_process_id) references membership_process;
alter table if exists mentorship_process
    add constraint FK_mentorship_process_member foreign key (mentor_id) references member;
